# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(598, 282)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.id = QtWidgets.QLineEdit(self.centralwidget)
        self.id.setGeometry(QtCore.QRect(20, 40, 171, 20))
        self.id.setObjectName("id")
        self.pwd = QtWidgets.QLineEdit(self.centralwidget)
        self.pwd.setGeometry(QtCore.QRect(210, 40, 181, 20))
        self.pwd.setObjectName("pwd")
        self.nick = QtWidgets.QLineEdit(self.centralwidget)
        self.nick.setGeometry(QtCore.QRect(400, 40, 181, 20))
        self.nick.setObjectName("nick")
        self.cafe = QtWidgets.QLineEdit(self.centralwidget)
        self.cafe.setGeometry(QtCore.QRect(20, 100, 171, 20))
        self.cafe.setObjectName("cafe")
        self.category = QtWidgets.QLineEdit(self.centralwidget)
        self.category.setGeometry(QtCore.QRect(210, 100, 181, 20))
        self.category.setObjectName("category")
        self.keyword = QtWidgets.QLineEdit(self.centralwidget)
        self.keyword.setGeometry(QtCore.QRect(400, 100, 181, 20))
        self.keyword.setObjectName("keyword")
        self.comment = QtWidgets.QTextEdit(self.centralwidget)
        self.comment.setGeometry(QtCore.QRect(20, 160, 471, 91))
        self.comment.setObjectName("comment")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 101, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 10, 101, 31))
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(410, 10, 101, 31))
        self.label_8.setObjectName("label_8")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 70, 101, 31))
        self.label_3.setObjectName("label_3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(410, 70, 101, 31))
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(220, 70, 101, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 130, 101, 31))
        self.label_5.setObjectName("label_5")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(500, 160, 81, 91))
        self.btn_start.setObjectName("btn_start")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 56, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(210, 10, 56, 31))
        self.label_7.setObjectName("label_7")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(400, 10, 56, 31))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(20, 70, 56, 31))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(210, 70, 56, 31))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(20, 130, 56, 31))
        self.label_13.setObjectName("label_13")

        self.label_6.setStyleSheet("Color : red")
        self.label_7.setStyleSheet("Color : red")
        self.label_10.setStyleSheet("Color : red")
        self.label_11.setStyleSheet("Color : red")
        self.label_12.setStyleSheet("Color : red")
        self.label_13.setStyleSheet("Color : red")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 598, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "아이디"))
        self.label_2.setText(_translate("MainWindow", "비밀번호"))
        self.label_8.setText(_translate("MainWindow", "카페 닉네임"))
        self.label_3.setText(_translate("MainWindow", "카페 이름"))
        self.label_9.setText(_translate("MainWindow", "키워드"))
        self.label_4.setText(_translate("MainWindow", "게시판 이름"))
        self.label_5.setText(_translate("MainWindow", "댓글"))
        self.btn_start.setText(_translate("MainWindow", "시작"))
        self.label_6.setText(_translate("MainWindow", "*"))
        self.label_7.setText(_translate("MainWindow", "*"))
        self.label_10.setText(_translate("MainWindow", "*"))
        self.label_11.setText(_translate("MainWindow", "*"))
        self.label_12.setText(_translate("MainWindow", "*"))
        self.label_13.setText(_translate("MainWindow", "*"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
